#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
minecraft_version=26.1
minecraft_version_range=~26.1
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_id=adrift
mod_name=Adrift
mod_description=Rift addon for Odin
mod_version=0.0.1
archives_base_name=adrift
# Mod Dependencies
fabric_kotlin_version=1.13.12+kotlin.2.4.0
fabric_api_version=0.151.0+26.1.2
devauth_version=1.2.2
commodore_version=1.0.1
# Other Properties
kotlin_version=2.4.0
kotlin.code.style=official
minecraft_lwjgl_version=3.4.1

# you can put here either version number (0.0.4) or commit hashes
odin_version=0.3.2
